apiVersion: v1
kind: Pod
metadata:
  name: nodehello-world-test.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: wardviane/k8s-demo
    ports:
    - name: nodejs-port
      containerPort: 3000
